### ISSUE TITLE
LU translation functions don't serialize

### ISSUE THREAD

**Issue by shyamd** [materialsproject/maggma#11]
The LU translator functions don't json serialize so the Store no longer dumps to json if you use one of them. I'll leave it up to you to decide how you want to deal with this. I'd think we might just have key type strings and the stores just translate to a standard internal format?

**Comment by dwinston** [comment]
I'm fine with e.g. `assert lu_key in ['datetime', 'isoformat']` and mapping those `str` keys to the current function-pairs. I'm not interested in supporting other `lu_field` formats. I don't think any other formats are in use by anyone.

**Comment by shyamd** [comment]
fixed in https://github.com/materialsproject/maggma/commit/58b3e4e7be0fca01fdfba47d5aca8ae7dd318b20
