### ISSUE TITLE
ISSUE: newer_in method incompatible with GridFSStore

### ISSUE THREAD

**Issue by munrojm** [materialsproject/maggma#113]
The `_collection` property of GridFSStore does not work with `confirm_field_index` which gets called when `newer_in` is used.

**Comment by shyamd** [comment]
This should have been fixed as of https://github.com/materialsproject/maggma/commit/96f4f6f912ae70e9196ead9722d523f0910aa24e#diff-4fcabb2371d3be354d6c5db6e979bd6d

Can you confirm?

**Comment by munrojm** [comment]
Yup, looks as though it is working well!
