### ISSUE TITLE
FEATURE: Serialized SSH Tunnel

### ISSUE THREAD

**Issue by shyamd** [materialsproject/maggma#290]
The SSH tunnel feature in `MongoStore` is really nice in python terminal or jupyter-notebook. Ideally, we could serialize the connection and have MongoStore initialize it when deserialized.

**Comment by mkhorton** [comment]
Seconded, this would be really useful. I've had builds break because of a flaky VPN.

**Comment by mkhorton** [comment]
Adding this to the docs would be appreciated too.

Alternatively, instead of making it serialized, an option on mrun e.g. `mrun --ssh dtn` where `dtn` is a host defined in your `~/.ssh/config` might be all that's needed.

**Comment by shyamd** [comment]
Implemented in #320
