### ISSUE TITLE
ditch python 2 and support only 3?

### ISSUE THREAD

**Issue by matk86** [materialsproject/maggma#3]

**Comment by shyuep** [comment]
I vote yes on this. This definitely deserves a discussion.

**Comment by dwinston** [comment]
I spoke with @matk86 and others, and I also vote for maggma being py3-only. It's a new project, and it can be run in an isolated environment if needed.

**Comment by computron** [comment]
I am not sure exactly what maggma is really about (I just had strong opinions on its naming) but Py3 sounds good to me
