### ISSUE TITLE
tqdm in Jupyter

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/maggma#33]
Should `from tqdm import tqdm_notebook as tqdm` when running inside Jupyter to avoid writing a billion progress bars. I'm not sure the cleanest way to check if running inside Jupyter however -- there seem to be a few options, none of them great.

**Comment by tschaume** [comment]
I've used `get_ipython` in the past to check for an interactive ipython (Jupyter) environment. So maybe something like the following could work here:

```
from IPython import get_ipython
ipython = get_ipython()
if ipython is not None:
    from tqdm import tqdm_notebook as tqdm
```

HTH

**Comment by mkhorton** [comment]
`get_ipython` will be True even if running from ipython command line no? so it's not Jupyter specific

**Comment by mkhorton** [comment]
The one thing I've found is `get_ipython().config` does return a dict with a `IPKernelApp` key if running inside Jupyter, but I'm not sure if that's guaranteed or not.

**Comment by dwinston** [comment]
Done via #34. Thanks @mkhorton!
