### ISSUE TITLE
Running JSONStore.connect() multiple times leads to undefined behavior

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/maggma#40]
I believe it'll either error out (BulkWriteOp error) or lead to duplicate documents, depending on if object _id has been serialized or not.

**Comment by shyamd** [comment]
JSONStore connect should really use self.update_targets to insert docs instead of direct insert_many. This does mean that each doc has to have a task_id, and I'm not yet certain that we should be enforcing that for JSONStore. If we do, should we just auto-assign that?

**Comment by mkhorton** [comment]
I don't really have an opinion as long as we're consistent, do all stores enforce a key requirement?

**Comment by shyamd** [comment]
Everything else does, so I guess this should too. Alright. I will put that on my todo list.

**Comment by shyamd** [comment]
Fixed by https://github.com/materialsproject/maggma/commit/f07b9d6435becffd8b75438c10d2f45bea189e78
