### ISSUE TITLE
Non-obvious error message when trying to query a Store that hasn't been connected

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/maggma#41]
`AttributeError: 'NoneType' object has no attribute 'find'`

Doubly-confusing because you're calling `Store.query()`, which is aliased to `collection.find()` ...

**Comment by shyamd** [comment]
Should be fixed with latest commit. Should have done it as a PR so I could ref it, but forgot to.

**Comment by mkhorton** [comment]
Thanks!
