### ISSUE TITLE
Add time limits to process_item? (Possibly just in MapBuilder?)

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/maggma#45]
I was about to add a time limit to BVAnalyzer since @shyamd mentioned some materials were taking too long to complete. However, this seems like it may be a common issue that some analysis tasks just take too long (perhaps pathologically so) for certain materials. A more general solution might be to add a time limit (and time limit kwarg) to process_items, possibly just in MapBuilder itself.

**Comment by shyamd** [comment]
I think I need to fundamentally rework the parallelization to use asyncio. There are a few places in the runner that are just not very efficient.

**Comment by mkhorton** [comment]
Isn't asyncio more for IO-bound tasks specifically? Not sure if our builders are IO-bound as much as CPU-bound

**Comment by shyamd** [comment]
asyncio was designed for that but basically, the builder infrastructure is the asynchronous execution of 3 things: get_items, process_item, and update_targets that are manually synchronized at key points. The futures framework used in python plugs right into asyncio, but you get added thigs like cancelling, wait shielding, etc. 

In terms of future scaling, this could also be a useful framework to think about scaling to AWS. If get_items yielded a coroutine to grab data, you could theoretically get infinite scaling with something like lambda + ddb

**Comment by shyamd** [comment]
Added in #54
