### ISSUE TITLE
Preserve last_updated for MapBuilder

### ISSUE THREAD

**Issue by shyamd** [materialsproject/maggma#58]
Add a feature to preserve the last_updated data in MapBuilder.

This is usefull for derived data collections where we lazily just recompute and update everytime we run that builder rather than only updating new things.

**Comment by dwinston** [comment]
What do you mean by “preserve”? MapBuilder normally doesn’t update the last_updated field of the target store.

**Comment by shyamd** [comment]
You're right. T'was a different builder that was the offender.
