### ISSUE TITLE
Onotology generation from builder

### ISSUE THREAD

**Issue by shyamd** [materialsproject/maggma#59]
Another idea to think about:
How do we make it so that builders can also define the ontology? Is this just the pydantic model or can we have it define the rules for how something maps to another. That is can we define the connections a builder is supposed to create in a standard ontology language without making this onerous.

**Comment by dwinston** [comment]
I assume you're referencing [this talk](https://github.com/materialsproject/maggma/files/3387384/Lambrix-intro-to-ontologies-and-ontology-engineering.pdf) at the [workshop in Berlin](https://th.fhi-berlin.mpg.de/meetings/meta2019/index.php?n=Meeting.Program) you attended this week? I don't know much about ontology engineering. Perhaps we can go over Lambrix's slides together sometime.

**Comment by shyamd** [comment]
I think this is outside of the scope of what we want to build. I'm closing this for now since its a bit too pie in the sky.
