### ISSUE TITLE
Blowfish has been deprecated

### ISSUE THREAD

**Issue by arosen93** [materialsproject/maggma#678]
In Python 3.9.12 and `maggma==0.47.2`, I get the following deprecation warning after running `from maggma.stores import MongoStore`.

```python
C:\Users\asros\miniconda\envs\cms\lib\site-packages\paramiko\transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
```

I don't really have a clue where it is being called. The name is great though.

**Comment by rkingsbury** [comment]
It looks like this was [fixed ](https://github.com/paramiko/paramiko/issues/2038) in a newer version of `paramiko` (>=2.11), which is a dependency of `sshtunnel` which we have in the `maggma` requirements. Unfortunately it seems like the latest version of `sshtunnel` only [requires ](https://github.com/pahaz/sshtunnel/blob/master/setup.py#L100) `paramiko>2.7`.

So I think you can fix this on your system by upgrading `paramiko`. If you want, feel free to post a PR over at `sshtunnel` asking them to update their requirements to >2.11
