### ISSUE TITLE
[Bug] MongoURIStore not able to access some parent attributes.

### ISSUE THREAD

**Issue by jmmshn** [materialsproject/maggma#684]
https://github.com/materialsproject/maggma/blob/df713a2a920502a85469e69178ecd1ff18c1a78b/src/maggma/stores/mongolike.py#L557

This constructor is bypassing the one for `MongoStore` and as a result it does not populate some attributes that are needed by the methods inherited from `MongoStore`.  (i.e. `self.safe_update`)

**Comment by rkingsbury** [comment]
Discussion continued in #1013
