### ISSUE TITLE
Instantiating a `Store` from a dictionary representation

### ISSUE THREAD

**Issue by arosen93** [materialsproject/maggma#825]
I want to be able to instantiate a Maggma data store from a dictionary representation, without knowing in advance what kind of data store it may be. I was hoping that the following might work, but it doesn't. Any alternate ideas? I don't want to use `loadfn`/`dumpfn` from `monty` because then it's tied to a specific file, which I'm trying to avoid.

```python
from maggma.stores import MemoryStore, Store

mystore = MemoryStore()
d = mystore.as_dict()
Store.from_dict(d)
```
```
    190 """
    191 :param d: Dict representation.
    192 :return: MSONable class.
    193 """
    194 decoded = {k: MontyDecoder().process_decoded(v) for k, v in d.items() if not k.startswith("@")}
--> 195 return cls(**decoded)

TypeError: Can't instantiate abstract class Store with abstract methods _collection, close, connect, count, ensure_index, groupby, name, query, remove_docs, update
```
The motivation for this is what I would like to provide a Pydantic settings file where the user can specify a Maggma data store. I figured a `dict` with `.as_dict()` (or `str` with `.to_json()`) representation would be the easiest way to format the field.  Jobflow does this already, but it goes about it in a somewhat complicated way that I was hoping to avoid.

**Comment by arosen93** [comment]
I'm closing this because I realize in hindsight it's rather silly.

The best solution would be to take the `.as_dict()` representation of the Maggma data store, which has the module and class names in it already, and then use that to use the appropriate `.from_dict()` method.

For instance, `MemoryStore().as_dict()` yields
```
{'@module': 'maggma.stores.mongolike',
 '@class': 'MemoryStore',
 '@version': '0.51.19',
 'collection_name': 'memory_db'}
```

That means it's trivial to know that we should use `MemoryStore().from_dict()`, which will reconstruct it automatically.

**Comment by mkhorton** [comment]
You can also use `MontyDecoder` without any special logic.

**Comment by arosen93** [comment]
@mkhorton: Thanks!! I was looking for something like!
