### ISSUE TITLE
Would the maggma docs be a good place to host MongoDB setup instructions? 

### ISSUE THREAD

**Issue by arosen93** [materialsproject/maggma#845]
I wrote up this short snippet for setting up a MongoDB Atlas account. I figured maggma could be a good place to put it, but it didn't seem like there was a particularly good spot in the docs. Any suggestions? 

-----

Most users find MongoDB to best suit their needs. The easiest route to create a Mongo database is via a cloud storage solution called [MongoDB Atlas](https://www.mongodb.com/atlas), which has a free tier. The setup instructions are described below:

1. Sign up for a free account on [MongoDB Atlas](https://www.mongodb.com/atlas).
2. Once logged in, select the "Create a Project" option and give your project a name (e.g. "MyProject"). Add your email address as the Project Owner.
3. Click the "Build a Database" button under the "Deployment > Database" section and choose the free (i.e. M0) option. Give your cluster a unique name (e.g. "MyCluster").
4. Select "Create" and enter your desired login credentials that you will use to access your database. You are probably best off not using special characters here since it will be URL-encoded. You should also use different credentials than your usual, since it's not uncommon to share credentials with trusted colleagues. Select "Finish and Close" when done.
5. Go to the "Collections" tab of your cluster, which is where you will create a database (e.g. "my_database") and corresponding data collection (e.g. "my_collection") by clicking the "Add My Own Data" button.
6. Under the "Security > Network Access" section, edit the IP Access List to allow access from anywhere for maximum flexibility.
7. Finally, retrieve your MongoDB URI, which is the address of your MongoDB cluster. You can find your database's URI by clicking the "Database" section in the sidebar and then selecting "Connect > Compass" and copying the link of the form `mongodb+srv://<username>:<password>@<host>`.

To test that you can connect to your database, run the following code:

```python
from maggma.stores import MongoURIStore

# Define your database credentials
store = MongoURIStore(
    "mongodb+srv://<username>:<password>@<host>",
    "my_collection",
    database="my_database",
)

# Query the database
with store:
    print(store.count())
```

!!! Note

    If you are using a self-hosted Mongo database, you will probably want to use a [`MongoStore`](https://materialsproject.github.io/maggma/reference/stores/#maggma.stores.mongolike.MongoStore) instead of the [`MongoURIStore`](https://materialsproject.github.io/maggma/reference/stores/#maggma.stores.mongolike.MongoURIStore), which takes slightly different arguments.

**Comment by rkingsbury** [comment]
Thanks @arosen93 ! I absolutely support including this in the docs. Since `Store.query()` is based on MongoDB query syntax, I would also like to include in the docs a brief tutorial on the basics of that syntax, which is right in line with this contribution.

For now, I'm inclined to say this should go in a new page called 'Setting up MongoDB' under the 'Getting Started' section of the docs. We might reorganize a little bit if/when we get around to adding more expanded tutorials.

**Comment by arosen93** [comment]
@rkingsbury: Sounds good! That all makes sense to me 😄 I'll submit a PR. Feel free to ping me if I forget though.
