### ISSUE TITLE
Support for Pydantic 2

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/maggma#858]
I know @munrojm is already on this. This issue is mainly so I can keep tabs on when this is addressed :)

Related entries in the MP ecosystem:
- https://github.com/materialsvirtuallab/monty/pull/548
- https://github.com/materialsproject/emmet/issues/768
- https://github.com/materialsproject/jobflow/issues/422
- https://github.com/materialsproject/pymatgen/issues/3301

**Comment by munrojm** [comment]
Pydantic 2.0 is supported as of the latest release

**Comment by mkhorton** [comment]
Nice work on this! Hopefully it results in some good perf gains too :)
