### ISSUE TITLE
Update README/docs to better reflect the purpose of Maggma

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/maggma#886]
### Problem

In talking to colleagues unfamiliar with maggma, when they check out the repo, it seems there is some (justifiable) confusion about the main purpose of the package.

For instance, the "About" section on the GitHub sidebar says "MongoDB aggregation machine", which of course is how the name was derived, but it leads visitors to believe that it is a package only for MongoDB when in reality there are many data stores.

The README says "A files-to-API data pipeline," but in fact, many of the data stores do not rely on the filesystem at all. The same point can be made for the "What is Maggma" section of [the documentation](https://materialsproject.github.io/maggma/#what-is-maggma).

In general, it is not immediately clear the purpose of Maggma from the docs, and there is a lot of jargon once you dive into the docs.

### Proposed Solution

1. Come up with some clearer branding on the README and "What is Maggma" section.
2. Add a "quickstart" section to the Maggma docs, before the Core Concepts, that shows a common minimal example. For instance, instantiate a `MongoStore`, upload a toy result, and query it.

**Comment by rkingsbury** [comment]
Great ideas @Andrew-S-Rosen , I am strongly in favor (and have been wanting to do something like this for a while.) I am happy to take a stab at it, but it will likely be mid-December of later before I can do it. I'll tackle #702 at the same time.
