### ISSUE TITLE
Query Engine equivalent

### ISSUE THREAD

**Issue by shyamd** [materialsproject/maggma#9]
There are a lot of key capabilities that need to be wrapped into some class such as query engine that implements find and return capabilities agnostic of find, distinct, etc.
- This is important to wrap all the different way data can be accessed, e.g. direct mongo or gridFS
- Implement the same flat properties that pymatgen-db QueryEngine implements?
- implicit sandboxing
- provide structure agnostic access for data. 
- eventual usage of aggregation pipelines across collections

**Comment by shyamd** [comment]
Began working on this by implementing an AliasingStore. I imagine all of this functionality can be layered by creating the appropriate advanced store. This does require that all buidlers use the accessors provided by store rather then trying to use the collections themselves.

**Comment by dwinston** [comment]
@shyamd please update with current status given various new recent additions.

**Comment by shyamd** [comment]
At this point we have:
- Aliasing
- Sandboxing

There are some materials specific access patterns, but I'm not sure those should be in the store. I think this is mostly done.
