### ISSUE TITLE
[Feature Request]: Support numpy 2.0

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/maggma#990]
### Problem

This is just an issue report to track progress towards removing the `numpy<2` pin in `pyproject.toml`: https://github.com/materialsproject/maggma/blob/64115cefc8e11716b458e03f195e28e49304ba13/pyproject.toml#L40. 

### Proposed Solution

None at this time. I don't know the original motivation, but Pymatgen now supports numpy 2.0.

**Comment by rkingsbury** [comment]
Thanks @Andrew-S-Rosen . I don't recall why I had to do this originally, but I know that shortly after `numpy` 2.0 was released I encountered some issue with a d/s dependency. Hopefully will have this merged soon over in #991
